//! Signed service admission. Kept byte-identical in Indexer/Matcher; the wire fixture is
//! generated by Asset Service. No chain keys, user keys, service URLs, or arbitrary calls.
use k256::ecdsa::{signature::hazmat::PrehashVerifier, Signature, VerifyingKey};
use serde::Deserialize;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{
    fs,
    io::Write,
    path::PathBuf,
    sync::{Arc, Mutex, OnceLock},
};

type Result<T> = std::result::Result<T, String>;
const MAX_BYTES: u64 = 16 * 1024 * 1024;
#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Key {
    key_id: String,
    public_key: String,
    not_before: u64,
    expires_at: u64,
}
#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Trust {
    chain_id: u64,
    genesis_hash: String,
    profile_id: String,
    factory: String,
    implementation: String,
    quote_pool: String,
    verifier_set_id: String,
    artifact_profile_id: String,
    note_decimals: u64,
    keys: Vec<Key>,
}
#[derive(Clone, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct Config {
    trust: Trust,
    minimum_revision: String,
}
struct State {
    envelope: Option<Arc<Value>>,
    encoded: Option<Vec<u8>>,
    hash: Option<String>,
}
pub(crate) struct Gate {
    config: Config,
    snapshot: PathBuf,
    checkpoint: PathBuf,
    state: Mutex<State>,
}
fn field<'a>(v: &'a Value, k: &str) -> Result<&'a str> {
    v[k].as_str().ok_or_else(|| format!("invalid catalog {k}"))
}
fn integer(v: &Value, k: &str) -> Result<u64> {
    v[k].as_u64()
        .filter(|n| *n <= 9007199254740991)
        .ok_or_else(|| format!("invalid catalog {k}"))
}
fn revision(v: &Value) -> Result<u64> {
    let s = field(v, "revision")?;
    let n = s.parse::<u64>().map_err(|_| "invalid catalog revision")?;
    if n == 0 || n.to_string() != s {
        return Err("non-canonical catalog revision".into());
    }
    Ok(n)
}
fn hex_bytes(s: &str) -> Result<Vec<u8>> {
    hex::decode(s.strip_prefix("0x").ok_or("missing hex prefix")?).map_err(|_| "invalid hex".into())
}
fn encoded(v: &Value) -> Result<Vec<u8>> {
    // Sort explicitly: a transitive serde_json/preserve_order feature must not change wire
    // signatures. Never pass amounts/revisions through floating point.
    fn emit(v: &Value) -> Result<String> {
        match v {
            Value::Number(n) if !n.as_u64().is_some_and(|n| n <= 9007199254740991) => {
                Err("non-canonical catalog number".into())
            }
            Value::Array(a) => Ok(format!(
                "[{}]",
                a.iter().map(emit).collect::<Result<Vec<_>>>()?.join(",")
            )),
            Value::Object(o) => {
                let mut keys: Vec<_> = o.keys().collect();
                keys.sort();
                Ok(format!(
                    "{{{}}}",
                    keys.into_iter()
                        .map(|k| Ok(format!(
                            "{}:{}",
                            serde_json::to_string(k).map_err(|_| "key encoding failed")?,
                            emit(&o[k])?
                        )))
                        .collect::<Result<Vec<_>>>()?
                        .join(",")
                ))
            }
            _ => serde_json::to_string(v).map_err(|_| "catalog encoding failed".into()),
        }
    }
    Ok(emit(v)?.into_bytes())
}
fn hash(v: &Value) -> Result<String> {
    Ok(format!("0x{}", hex::encode(Sha256::digest(encoded(v)?))))
}
fn read(path: &PathBuf) -> Result<Vec<u8>> {
    use std::io::Read;
    let mut file = fs::File::open(path).map_err(|_| "catalog input unavailable")?;
    let mut b = Vec::new();
    std::io::Read::by_ref(&mut file)
        .take(MAX_BYTES + 1)
        .read_to_end(&mut b)
        .map_err(|_| "catalog read failed")?;
    if b.len() as u64 > MAX_BYTES {
        return Err("catalog size exceeded".into());
    }
    Ok(b)
}
fn persist(path: &PathBuf, bytes: &[u8]) -> Result<()> {
    let tmp = path.with_extension(format!("tmp-{}", std::process::id()));
    let mut options = fs::OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let mut f = options
        .open(&tmp)
        .map_err(|_| "catalog checkpoint create failed")?;
    let result = (|| {
        f.write_all(bytes)?;
        f.sync_all()?;
        fs::rename(&tmp, path)?;
        fs::File::open(path.parent().unwrap_or(std::path::Path::new(".")))?.sync_all()
    })()
    .map_err(|_| "catalog checkpoint persistence failed".to_string());
    if result.is_err() {
        let _ = fs::remove_file(tmp);
    }
    result
}
impl Gate {
    fn new(config: Config, snapshot: PathBuf, checkpoint: PathBuf) -> Result<Self> {
        let old = if checkpoint.exists() {
            Some(
                serde_json::from_slice(&read(&checkpoint)?)
                    .map_err(|_| "invalid catalog checkpoint")?,
            )
        } else {
            None
        };
        Ok(Self {
            config,
            snapshot,
            checkpoint,
            state: Mutex::new(State {
                envelope: old.map(Arc::new),
                encoded: None,
                hash: None,
            }),
        })
    }
    fn verify(&self, e: &Value, now: u64, history: bool) -> Result<()> {
        let t = &self.config.trust;
        let p = &e["payload"];
        let rev = revision(p)?;
        if rev
            < self
                .config
                .minimum_revision
                .parse::<u64>()
                .map_err(|_| "invalid release revision floor")?
            || field(p, "schema")? != "perc20-asset-catalog/v1"
            || integer(p, "chainId")? != t.chain_id
            || field(p, "genesisHash")? != t.genesis_hash
            || field(p, "profileId")? != t.profile_id
        {
            return Err("catalog trust scope mismatch".into());
        }
        let issued = integer(p, "issuedAt")?;
        let expires = integer(p, "expiresAt")?;
        let key = t
            .keys
            .iter()
            .find(|k| e["keyId"].as_str() == Some(k.key_id.as_str()))
            .ok_or("unknown catalog key")?;
        if issued < key.not_before
            || expires > key.expires_at
            || expires <= issued
            || expires - issued > 3600
            || issued > now.saturating_add(30)
            || (!history && now >= expires)
        {
            return Err("catalog lease expired or invalid".into());
        }
        let vk = VerifyingKey::from_sec1_bytes(&hex_bytes(&key.public_key)?)
            .map_err(|_| "invalid catalog public key")?;
        let sig = Signature::from_slice(&hex_bytes(field(e, "signature")?)?)
            .map_err(|_| "invalid catalog signature")?;
        if sig.normalize_s().is_some() {
            return Err("non-canonical catalog signature".into());
        }
        let mut msg = format!("PERC20-ASSET-CATALOG-V1\n{}\n", key.key_id).into_bytes();
        msg.extend(encoded(p)?);
        vk.verify_prehash(&Sha256::digest(msg), &sig)
            .map_err(|_| "catalog signature rejected")?;
        let assets = p["assets"].as_array().ok_or("missing catalog assets")?;
        if assets.len() > 10000 {
            return Err("catalog asset capacity exceeded".into());
        }
        let mut previous = "";
        for a in assets {
            let security = field(a, "securityRevision")?;
            let security_number = security
                .parse::<u64>()
                .map_err(|_| "invalid security revision")?;
            if security_number == 0
                || security_number.to_string() != security
                || !["active", "recovery-only"].contains(&field(a, "status")?)
            {
                return Err("invalid asset security state".into());
            }
            let pool = field(a, "pool")?;
            let id = field(a, "assetId")?;
            if pool.len() != 42
                || hex_bytes(pool)?.len() != 20
                || pool != pool.to_lowercase()
                || pool == format!("0x{}", "00".repeat(20))
                || id != format!("{}:{}", t.chain_id, pool)
                || id <= previous
            {
                return Err("invalid catalog asset identity".into());
            }
            previous = id;
            if field(&a["deployment"], "factory")? != t.factory
                || field(a, "implementation")? != t.implementation
                || field(a, "quotePool")? != t.quote_pool
                || integer(a, "noteDecimals")? != t.note_decimals
                || integer(&a["protocol"], "version")? != 3
                || field(&a["protocol"], "abiProfile")? != "current-v2"
                || field(&a["protocol"], "verifierSetId")? != t.verifier_set_id
                || field(&a["protocol"], "artifactProfileId")? != t.artifact_profile_id
            {
                return Err("asset outside release template".into());
            }
            let r = &a["readiness"];
            if integer(r, "validUntil")? < expires
                || integer(r, "checkedBlock")? < integer(&a["deployment"], "blockNumber")?
            {
                return Err("invalid asset readiness".into());
            }
            for op in ["sync", "rootConfirmation", "transfer", "ammTrade"] {
                if !a["capabilities"][op].is_boolean() {
                    return Err("invalid capability".into());
                }
            }
            if a["capabilities"]["transfer"] == true || a["capabilities"]["ammTrade"] == true {
                if a["status"] != "active"
                    || a["capabilities"]["sync"] != true
                    || a["capabilities"]["rootConfirmation"] != true
                    || integer(r, "indexedThrough")? < integer(r, "checkedBlock")?
                {
                    return Err("asset not ready".into());
                }
            }
        }
        Ok(())
    }
    fn load(&self, now: u64) -> Result<(Arc<Value>, String)> {
        let bytes = read(&self.snapshot)?;
        let mut s = self.state.lock().map_err(|_| "catalog lock poisoned")?;
        if s.encoded.as_ref() == Some(&bytes) {
            let e = s.envelope.as_ref().ok_or("empty catalog state")?;
            if integer(&e["payload"], "expiresAt")? <= now {
                return Err("catalog expired".into());
            }
            return Ok((e.clone(), s.hash.clone().ok_or("missing catalog hash")?));
        }
        let e: Value = serde_json::from_slice(&bytes).map_err(|_| "invalid catalog JSON")?;
        self.verify(&e, now, false)?;
        if let Some(old) = s.envelope.as_ref() {
            self.verify(old, now, true)?;
            let a = revision(&old["payload"])?;
            let b = revision(&e["payload"])?;
            if b < a || (b == a && hash(&old["payload"])? != hash(&e["payload"])?) {
                return Err("catalog rollback/equivocation".into());
            }
            if b == a + 1 && field(&e["payload"], "previousHash")? != hash(&old["payload"])? {
                return Err("broken catalog hash chain".into());
            }
            let current_assets: std::collections::BTreeMap<_, _> = e["payload"]["assets"]
                .as_array()
                .unwrap()
                .iter()
                .map(|a| (a["assetId"].as_str().unwrap(), a))
                .collect();
            for prior in old["payload"]["assets"]
                .as_array()
                .ok_or("old catalog assets missing")?
            {
                let current = *current_assets
                    .get(field(prior, "assetId")?)
                    .ok_or("catalog erased historical asset")?;
                for k in [
                    "assetId",
                    "pool",
                    "creator",
                    "deployment",
                    "protocol",
                    "implementation",
                    "quotePool",
                    "noteDecimals",
                ] {
                    if current[k] != prior[k] {
                        return Err("catalog changed immutable recovery identity".into());
                    }
                }
                let old_r = field(prior, "securityRevision")?
                    .parse::<u64>()
                    .map_err(|_| "invalid security revision")?;
                let new_r = field(current, "securityRevision")?
                    .parse::<u64>()
                    .map_err(|_| "invalid security revision")?;
                if new_r < old_r
                    || ((prior["status"] != current["status"]
                        || prior["capabilities"] != current["capabilities"])
                        && new_r <= old_r)
                {
                    return Err("security revision rollback".into());
                }
            }
        }
        let h = hash(&e["payload"])?;
        let e = Arc::new(e);
        persist(&self.checkpoint, &bytes)?;
        s.envelope = Some(e.clone());
        s.encoded = Some(bytes);
        s.hash = Some(h.clone());
        Ok((e, h))
    }
    pub(crate) fn check(&self, pool: &str, operation: &str, now: u64) -> Result<Value> {
        let (e, h) = self.load(now)?;
        let p = &e["payload"];
        let a = p["assets"]
            .as_array()
            .unwrap()
            .iter()
            .find(|a| a["pool"].as_str() == Some(pool))
            .ok_or("asset is not service-admitted")?;
        if !["sync", "rootConfirmation", "transfer", "ammTrade"].contains(&operation)
            || a["capabilities"][operation] != true
            || integer(&a["readiness"], "validUntil")? <= now
        {
            return Err("asset capability unavailable".into());
        }
        if ["transfer", "ammTrade"].contains(&operation) && a["status"] != "active" {
            return Err("asset is recovery-only".into());
        }
        Ok(
            json!({"catalog_revision":field(p,"revision")?,"catalog_hash":h,"security_revision":field(a,"securityRevision")?,"chain_id":self.config.trust.chain_id,"pool":pool,"expires_at":integer(p,"expiresAt")?}),
        )
    }
}
static GATE: OnceLock<std::result::Result<Option<Gate>, String>> = OnceLock::new();
/// A separate read-only service credential; never reuse a chain signer or admin token.
pub(crate) fn readiness_authorized(bearer: Option<&str>) -> bool {
    let Ok(expected) = std::env::var("ASSET_READINESS_TOKEN") else {
        return false;
    };
    let Some(got) = bearer.and_then(|v| v.strip_prefix("Bearer ")) else {
        return false;
    };
    !expected.is_empty()
        && got.len() == expected.len()
        && got
            .bytes()
            .zip(expected.bytes())
            .fold(0u8, |x, (a, b)| x | (a ^ b))
            == 0
}
pub(crate) fn require(pool: &str, operation: &str) -> Result<Option<Value>> {
    let gate = GATE.get_or_init(|| {
        let Some(snapshot) = std::env::var_os("ASSET_ADMISSION_SNAPSHOT") else {
            return Ok(None);
        };
        let trust =
            std::env::var_os("ASSET_ADMISSION_TRUST").ok_or("ASSET_ADMISSION_TRUST required")?;
        let checkpoint = std::env::var_os("ASSET_ADMISSION_CHECKPOINT")
            .ok_or("ASSET_ADMISSION_CHECKPOINT required")?;
        let cfg = serde_json::from_slice(&read(&trust.into())?)
            .map_err(|_| "invalid admission trust config")?;
        Gate::new(cfg, snapshot.into(), checkpoint.into()).map(Some)
    });
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|_| "invalid clock")?
        .as_secs();
    match gate {
        Ok(Some(g)) => g.check(pool, operation, now).map(Some),
        Ok(None) => Ok(None),
        Err(e) => Err(e.clone()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn fixture() -> Value {
        serde_json::from_str(include_str!("catalog-admission-fixture.json")).unwrap()
    }
    #[test]
    fn node_signed_catalog_verifies_and_survives_consumer_restart() {
        let f = fixture();
        let dir = std::env::temp_dir().join(format!(
            "catalog-admission-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir(&dir).unwrap();
        let snapshot = dir.join("snapshot.json");
        let checkpoint = dir.join("checkpoint.json");
        fs::write(&snapshot, serde_json::to_vec(&f["envelope"]).unwrap()).unwrap();
        let config: Config =
            serde_json::from_value(json!({"trust":f["trust"],"minimumRevision":"1"})).unwrap();
        let gate = Gate::new(config.clone(), snapshot.clone(), checkpoint.clone()).unwrap();
        let pool = f["envelope"]["payload"]["assets"][256]["pool"]
            .as_str()
            .unwrap();
        assert_eq!(
            gate.check(pool, "ammTrade", 1800000001).unwrap()["catalog_revision"],
            "1"
        );
        assert!(gate.check(pool, "ammTrade", 1800000300).is_err());
        let gate = Gate::new(config, snapshot.clone(), checkpoint).unwrap();
        assert!(gate.check(pool, "transfer", 1800000001).is_ok());
        let mut corrupt = f["envelope"].clone();
        corrupt["payload"]["assets"][0]["symbol"] = json!("ATTACK");
        fs::write(&snapshot, serde_json::to_vec(&corrupt).unwrap()).unwrap();
        assert!(gate
            .check(pool, "transfer", 1800000001)
            .unwrap_err()
            .contains("signature"));
        fs::remove_dir_all(dir).unwrap();
    }
    #[test]
    fn candidate_cannot_extend_the_release_chain_or_implementation() {
        let f = fixture();
        let mut config: Config =
            serde_json::from_value(json!({"trust":f["trust"],"minimumRevision":"1"})).unwrap();
        config.trust.chain_id = 1;
        let gate = Gate::new(
            config,
            PathBuf::new(),
            std::env::temp_dir().join("absent-privacyfun-catalog-checkpoint-test"),
        )
        .unwrap();
        assert!(gate
            .verify(&f["envelope"], 1800000001, false)
            .unwrap_err()
            .contains("scope"));
    }
}
